### ISSUE TITLE
I'm unable to login

### ISSUE THREAD

**Issue by procodervit69** [CodeChefVIT/Quizzie#94]
Very Annoying unable to login. 
[https://streamable.com/654ayw](url)

**Comment by jugaldb** [comment]
> Very Annoying unable to login.
> [https://streamable.com/654ayw](url)

Hi, thanks for reaching out, the link your attached seems to be broken, we tested it out again, the features work for us, could you make sure that the link you attached is working correctly so that we can guide you through the issue you are facing,

Also can you confirm that you had confirmed you email via the code received either in your spam/inbox,

I guess the video service you've used for the screen record seems to be broken, you can also use alternatives like shareX, recordit.

**Comment by procodervit69** [comment]
copy paste the link in web browser
https://streamable.com/654ayw

**Comment by akshatvg** [comment]
Can you embed the video here? @procodervit69?

Or use Vimeo or something 😄

**Comment by procodervit69** [comment]
No. 
Security issues for me. 
Codechef people will threaten me.

**Comment by akshatvg** [comment]
Could you give us steps to recreate your problem and what error you’re facing?

We don’t want to open a malicious link either 😃

**Comment by akshatvg** [comment]
@procodervit69 please let us know if the bug you mentioned is now fixed.

Thanks for your help 😄
